version: "3.7"

services:

  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/myapp
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - /home/alvian/docker/compose/nginx_php/php:/var/www/myapp
      - /home/alvian/docker/compose/nginx_php/php.ini:/usr/local/etc/php/php.ini
